Fix type errors. (#599)
## Description

This PR fixes pre-commit warnings related to an untyped numpy function. 

Mypy complains that
`src/mqt/qecc/circuit_synthesis/synthesis_utils.py:128: error: Unused
"type: ignore" comment [unused-ignore]`, but removing the ignore pragma
leads mypy to complain that
`src/mqt/qecc/circuit_synthesis/synthesis_utils.py:128: error: Call to
untyped function "array" in typed context [no-untyped-call]`. So
apparently, either is a problem. To make the CI run again, I just ignore
both errors in this line for now.

## Checklist:

<!---
This checklist serves as a reminder of a couple of things that ensure
your pull request will be merged swiftly.
-->

- [x] The pull request only contains commits that are focused and
relevant to this change.
- [x] I have added appropriate tests that cover the new/changed
functionality.
- [x] I have updated the documentation to reflect these changes.
- [x] I have added entries to the changelog for any noteworthy
additions, changes, fixes, or removals.
- [x] I have added migration instructions to the upgrade guide (if
needed).
- [x] The changes follow the project's style guidelines and introduce no
new warnings.
- [x] The changes are fully tested and pass the CI checks.
- [x] I have reviewed my own code changes.